namespace: producao
topologySpreadEnabled: true

image:
  tag: 04497b6

appVersion: "1.1.0"

ingress:
  host: app.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-producao
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: true
