namespace: homologacao
topologySpreadEnabled: false

image:
  tag: d23fc2f

appVersion: "1.2.0-homolog"

ingress:
  host: homolog.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-homolog
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: false
