namespace: producao
topologySpreadEnabled: false

image:
  tag: 2f9ccf0

appVersion: "1.1.0"

ingress:
  host: azure.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-producao-azure
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: true
