namespace: homologacao
topologySpreadEnabled: false

image:
  tag: d4a252f

appVersion: "1.1.0-homolog"

ingress:
  host: azure-homolog.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-homolog-azure
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: false
