namespace: producao
topologySpreadEnabled: true

image:
  tag: add54e5

appVersion: "1.2.0"

ingress:
  host: app.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-producao
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: true
