namespace: producao
topologySpreadEnabled: false

image:
  tag: 62c6a65

appVersion: "1.1.0"

ingress:
  host: azure.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-producao-azure
  clusterIssuer: letsencrypt-staging

hpa:
  enabled: true
