namespace: homologacao
topologySpreadEnabled: false

image:
  tag: add54e5

appVersion: "1.2.0-homolog"

ingress:
  host: homolog.lgpcloud.com.br
  tlsSecretName: conversao-distancia-tls-homolog
  clusterIssuer: letsencrypt-prod

hpa:
  enabled: false
